DROP TABLE IF EXISTS PEIXE, IMAGEM, LOCALIZACAO;
CREATE TABLE PEIXE (
	nome_peixe VARCHAR(100) PRIMARY KEY,
	caminho VARCHAR (250),
	descricao VARCHAR(400),
	tamanho VARCHAR (100),
	dificuldade VARCHAR (50)
	
);


CREATE TABLE LOCALIZACAO (
	id_localizacao SERIAL PRIMARY KEY,
	localizacao VARCHAR(500),
	hora VARCHAR (25),
	estacao VARCHAR (50),
	clima VARCHAR (50),
	nome_peixe VARCHAR(100) UNIQUE,
	FOREIGN KEY (nome_peixe) REFERENCES PEIXE(nome_peixe)
);

INSERT INTO PEIXE(nome_peixe, descricao, tamanho, dificuldade, caminho) VALUES 
('Baiacu','Infla quando ameaçado','3-94cm','80 flutuante','Peixe Stardew\Baiacu.png'),
('Anchova','Um pequeno peixe prateado encontrado no oceano','3-43cm','30 dardo','Peixe Stardew\Anchova.png'),
('Atum','Um grande peixe que vive no oceano','30-155cm','70 suave','Peixe Stardew\Atum.png'),
('Sardinha','Um peixe comum do oceano','3-33cm','30 dardo','Peixe Stardew\Sardinha.png'),
('Brema','Um peixe de água doce muito comum que fica ativo durante a noite','30-79cm','35 suave','Peixe Stardew\Brema.png'),
('Achigã','Um peixe popular que vive em lagos','28-79cm','50 misto','Peixe Stardew\Achigã.png'),
('Achigã-pequeno','Um peixe de água doce muito sensível à poluição','30-64cm','28 misto','Peixe Stardew\Achigã-pequeno.png'),
('Truta Arco-íris','Um peixe de água doce com marcas coloridas','25-66cm','45 misto','Peixe Stardew\Truta arco-íris.png'),
('Salmão','Nada corrente acima para por seus ovos','61-198cm','50 misto','Peixe Stardew\Salmão.png'),
('Picão-verde','Um peixe de água doce que pode ser capturado à noite','25-104cm','45 suave','Peixe Stardew\Picão-verde.png'),
('Perca','Um peixe de água fresca do inverno','25-64cm','35 dardo','Peixe Stardew\Perca.png'),
('Carpa','Um peixe comum de lago','38-130cm','15 misto','Peixe Stardew\Carpa.png'),
('Bagre','Um peixe incomum encontrado em correntes','30-185cm','75 misto','Peixe Stardew\Bagre.png'),
('Lúcio','Um peixe de água doce difícil de pegar','38-155cm','60 dardo','Peixe Stardew\Lúcio.png'),
('Peixe-sol','Um peixe muito comum em rios','13-41cm','30 misto','Peixe Stardew\Peixe-sol.png'),
('Salmonete','Há muito tempo, este peixe era mantido como animal de estimação','20-58cm','55 suave','Peixe Stardew\Salmonete.png'),
('Arenque','Um peixe comum de oceano','20-23cm','25 dardo','Peixe Stardew\Arenque.png'),
('Enguia','Um peixe alongado, escorregadio e pequeno','30-206cm','70 suave','Peixe Stardew\Enguia.png'),
('Polvo','Uma criatura misteriosa e inteligente','30-124cm','95 pesado','Peixe Stardew\Polvo.png'),
('Cioba','Um peixe popular com uma bonita cor vermelha','20-66cm','40 misto','Peixe Stardew\Cioba.png'),
('Lula','Uma criatura das profundezas do mar que pode ficar enorme','30-124cm','75 pesado','Peixe Stardew\Lula.png'),
('Pepino-do-mar','Uma criatura escorregadia e gosmenta encontrada no fundo do oceano','8-53cm','40 pesado','Peixe Stardew\Pepino-do-mar.png'),
('Superpepino','Uma variedade rara e púrpura de pepino-do-mar','30-94cm','80 pesado','Peixe Stardew\Superpepino.png'),
('Peixe-fantasma','Um peixe pálido e cego encontrado em lagos subterrâneos','25-91cm','50 misto','Peixe Stardew\Peixe-fantasma.png'),
('Peixe-pedra','Um peixe bizarro em forma de tijolo','36-38cm','65 pesado','Peixe Stardew\Peixe-pedra.png'),
('Chione','Um peixe raro que prospera em condições extremamente frias','18-23cm','85 dardo','Peixe Stardew\Chione.png'),
('Enguia de lava','Por algum motivo, consegue sobreviver em piscinas de lava superquente','79-81cm','90 misto','Peixe Stardew\Enguia-de-lava.png'),
('Areinha','Tenta se esconder se camuflando','20-64cm','65 misto','Peixe Stardew\Areinha.png'),
('Carpa Escorpiônica','Parece com uma carpa qualquer, mas tem um ferrão afiado','30-84cm','90 dardo','Peixe Stardew\Carpa escorpiônica.png'),
('Linguado','Ele vive no fundo, então os dois olhos estão no topo da cabeça','10-43cm','50 pesado','Peixe Stardew\Linguado.png'),
('Carpa da meia-noite','Este peixe tímido só se sente à noite','30-132cm','55 misto','Peixe Stardew\Carpa da meia-noite.png'),
('Esturjão','Um antigo peixe de fundo com uma população em queda. As fêmeas podem viver até 150 anos','30-155cm','78 misto','Peixe Stardew\Esturjão.png'),
('Salmão híbrido','Um salmão híbrido raro e estéril','25-53cm','60 dardo','Peixe Stardew\Salmão híbrido.png'),
('Peixe-gato-cabeçudo','Um parente do bagre que se alimenta do fundo de lagos','30-79cm','46 suave','Peixe Stardew\Peixe-gato-cabeçudo.png'),
('Tilápia','Um peixe herbívoro que prefere água quente','28-79cm','50 misto','Peixe Stardew\Tilápia.png'),
('Esquálio','Um peixe de água doce conhecido por seu apetite','12-25cm','35 dardo','Peixe Stardew\Esquálio.png'),
('Dourado','Um carnívoro inclemente com escamas laranjas brilhantes','61-84cm','78 misto','Peixe Stardew\Dourado.png'),
('Albacora','Prefere zonas de temperatura em que a água fria e quente se encontram','51-104cm','60 misto','Peixe Stardew\Albacora.png'),
('Alocine','Vive em cardumes em água salgada, mas volta aos rios para se reproduzir','51-124cm','45 suave','Peixe Stardew\Alocine.png'),
('Ófis','Um terrível predador que come quase qualquer coisa que consegue colocar na boca','76-130cm','85 misto','Peixe Stardew\Ófis.png'),
('Halibute','Um peixe chato que vive no fundo do oceano','25-86cm','50 pesado','Peixe Stardew\Halibute.png'),
('Madeirão','Um peixe muito sensível que só pode viver em lagos no meio da floresta','28-79cm','50 misto','Peixe Stardew\Madeirão.png'),
('Salmão nulo','Um salmão modificado por energia nula. A carne fresca é preta como carvão, mas fica rosa rapidamente quando exposta ao ar','61-165cm','80 misto','Peixe Stardew\Salmão nulo.png'),
('Salmão Mutante','Ele está coberto em uma camada de gosma espessa. Ele fica saindo das suas mãos','51-162cm','55 dardo','Peixe Stardew\Salmão Mutante.png'),
('Peixe-leão','Um peixe predatório e agressivo com espinhos venenosos','3-13cm','50 suave','Peixe Stardew\Peixe-leão.png'),
('Acará-disco-azul','Um peixe tropical de cor vibrante muito comum em aquários','2-10cm','60 dardo','Peixe Stardew\Acará-disco azul.png'),
('Gobi','Gosta de esconder em cachoeiras perto do esgoto','3-13cm','55 dardo','Peixe Stardew\Gobi.png'),
('Arraia','Mesmo tendo um espinho venenoso, estes peixes são tímidos e preferem evitar humanos','18-61cm','80 pesado','Peixe Stardew\Arraia.png'),
('Lula da meia-noite','Um cidadão estranho e misterioso das profundezas do oceano','20-64cm','55 pesado','Peixe Stardew\Lula da meia-noite.png'),
('Peixe assustador','Seus olhos enormes são capazes de detectar o contorno de suas presas','20-64cm','60 dardo','Peixe Stardew\Peixe Assustador.png'),
('Peixe-bolha','Esta estranha criatura flutua sobre o fundo do oceano, consumindo qualquer material comestível que estiver em seu caminho','20-64cm','75 flutuador','Peixe Stardew\Peixe-bolha.png'),
('Peixe-carmim','Vive nas profundezas do oceano, mas gosta de colocar seus ovos nas águas quentes de verão','48-53cm','95 misto','Peixe Stardew\Peixe-carmim.png'),
('Tamboril','Utiliza uma isca bioluminescente para atrair sua presa','43-53cm','85 suave','Peixe Stardew\Tamboril.png'),
('Lenda','O rei de todos os peixes! Disseram que jamais seria capturada','124-127cm','110 misto','Peixe Stardew\Lenda.png'),
('Peixe-gelo','Constrói um ninho na parte inferior das geleiras','66-71cm','100 misto','Peixe Stardew\Peixe-gelo.png'),
('Carpa mutante','As estranhas águas do esgoto transformaram esta carpa em uma monstruosidade','89-94cm','80 dardo','Peixe Stardew\Carpa mutante.png'),
('Filho do peixe-carmim','Ele nasceu na água quente do verão, e seguiu os passos de seu pai','48-53cm','95 misto','Peixe Stardew\Filho do peixe-carmim.png'),
('Senhorita tamboril','Utiliza uma isca bioluminescente para atrair sua presa','43-48cm','85 suave','Peixe Stardew\Senhorita tamboril.png'),
('Lenda 2','O sucessor da Lenda original','124-129cm','110 misto','Peixe Stardew\Lenda 2.png'),
('Peixe-gelo júnior','O Peixe-gelo original teve um filho...','66-71cm','100 misto','Peixe Stardew\Peixe-gelo júnior.png'),
('Carpa radioativa','Uma carpa que passou tempo demais nos esgotos','88-93cm','80 dardo','Peixe Stardew\Carpa radioativa.png'),
('Lagosta','Um crustáceo grande que vive no oceano. Possui uma grande cauda',NULL,NULL,'Peixe Stardew\Lagosta.png'),
('Concha','Alguém já viveu aqui',NULL,NULL,'Peixe Stardew\Concha.png'),
('Caranguejo','Um crustáceo marinho com duas puãs poderosas',NULL,NULL,'Peixe Stardew\Caranguejo.png'),
('Berbigão','Uma concha de água salgada muito comum',NULL,NULL,'Peixe Stardew\Berbigão.png'),
('Mexilhão','Um bivalve muito comum que geralmente vive em grupo',NULL,NULL,'Peixe Stardew\Mexilhão.png'),
('Camarão','Um necrófago que se alimenta do fundo do oceano. Sua carne é muito apreciada',NULL,NULL,'Peixe Stardew\Camarão.png'),
('Ostra','Filtra água constantemente para se alimentar. Durante o processo, remove toxinas perigosas para o meio ambiente',NULL,NULL,'Peixe Stardew\Ostra.png'),
('Lagostim','Um pequeno peixe de água doce parente da lagosta',NULL,NULL,'Peixe Stardew\Lagostim.png'),
('Lesma','Um molusco amplo muito comum que vive numa casca em espiral',NULL,NULL,'Peixe Stardew\Lesma.png'),
('Caramujo','Um molusco de água doce que vive em um casco azul',NULL,NULL,'Peixe Stardew\Caramujo.png'),
('Algas marinhas','Podem ser utilizadas na cozinha',NULL,NULL,'Peixe Stardew\Algas marinhas.png'),
('Algas verdes','São bem gosmentas',NULL,NULL,'Peixe Stardew\Algas verdes.png'),
('Algas brancas','São supergosmentas',NULL,NULL,'Peixe Stardew\Algas brancas.png'),
('Geléia do mar','Uma geléia rara encontrada no oceano',NULL,NULL,'Peixe Stardew\Geléia do mar.png'),
('Geléia do rio','Uma geléia rara encontrada em água doce',NULL,NULL,'Peixe Stardew\Geléia do rio.png'),
('Geléia da caverna','Uma geléia rara encontrada em lagos subterrâneos',NULL,NULL,'Peixe Stardew\Geléia da caverna.png')
;


INSERT INTO LOCALIZACAO(localizacao, hora, estacao, clima, nome_peixe) VALUES
('Oceano','12:00-16:00','Verão','Sol','Baiacu'),
('Oceano','6:00-2:00','Primavera/Outono','Sol/Chuva','Anchova'),
('Oceano','6:00-19:00','Verão/Inverno','Sol/Chuva','Atum'),
('Oceano','6:00-19:00','Primavera/Outono/Inverno','Sol/Chuva','Sardinha'),
('Rio da Cidade/Rio da Floresta','18:00-2:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Brema'),
('Lago da Montanha','6:00-19:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Achigã'),
('Rio da Cidade/Lago da Floresta','06:00-02:00','Primavera/Outono','Sol/Chuva','Achigã-pequeno'),
('Rio da Cidade/Rio da Floresta/Lago da Montanha','6:00-19:00','Verão','Sol','Truta Arco-íris'),
('Rio da Cidade/Rio da Floresta','6:00-19:00','Outono','Sol/Chuva','Salmão'),
('Rio da Cidade/Rio da Floresta/Lago da Floresta','12:00-2:00','Outono/Inverno','Chuva','Picão-verde'),
('Rio da Cidade/Rio da Floresta/Lago da Floresta/Lago da Montanha','06:00-02:00','Inverno','Sol/Chuva','Perca'),
('Lago da Montanha/Lago do Bosque Secreto/Esgotos','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Carpa'),
('Rio da Cidade/Rio da Floresta/Lago do Bosque Secreto/Pântano da Bruxa','6:00-00:00','Primavera/Outono/Verão (Lago do Bosque Secreto)','Chuva','Bagre'),
('Rio da Cidade/Rio da Floresta/Lago da Floresta','06:00-02:00','Verão/Inverno','Sol/Chuva','Lúcio'),
('Rio da Cidade/Rio da Floresta','6:00-19:00','Primavera/Verão','Sol/Vento','Peixe-sol'),
('Oceano','6:00-19:00','Verão/Inverno','Sol/Chuva','Salmonete'),
('Oceano','06:00-02:00','Primavera/Inverno','Sol/Chuva','Arenque'),
('Oceano','16:00-2:00','Primavera/Outono','Chuva','Enguia'),
('Oceano','6:00-13:00','Verão','Sol/Chuva','Polvo'),
('Oceano','6:00-19:00','Outono/Inverno','Chuva','Cioba'),
('Oceano','18:00-2:00','Inverno','Sol/Chuva','Lula'),
('Oceano','6:00-19:00','Outono/Inverno','Sol/Chuva','Pepino-do-mar'),
('Oceano/Oceano da Ilha Gengibre','18:00-2:00','Verão/Outono','Sol/Chuva','Superpepino'),
('Mina (20º e 60º andar)','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Peixe-fantasma'),
('Mina (20º andar)','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Peixe-pedra'),
('Mina (60º andar)','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Chione'),
('Mina (100º andar)','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Enguia de lava'),
('Deserto','6:00-20:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Areinha'),
('Deserto','6:00-20:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Carpa Escorpiônica'),
('Oceano/Oceano da Ilha Gengibre','6:00-20:00','Primavera/Verão','Sol/Chuva','Linguado'),
('Lago da Montanha/Lago da Ilha Gengibre/Rio da Ilha Gengibre','22:00-2:00','Outono/Inverno','Sol/Chuva','Carpa da meia-noite'),
('Lago da Montanha','6:00-19:00','Verão/Inverno','Sol/Chuva','Esturjão'),
('Rio da Cidade/Rio da Floresta','6:00-19:00','Outono/Inverno','Sol/Chuva','Salmão híbrido'),
('Lago da Montanha','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Peixe-gato-cabeçudo'),
('Oceano/Rio da Ilha Gengibre','6:00-14:00','Verão/Outono','Sol/Chuva','Tilápia'),
('Rio da Floresta/Lago da Montanha','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Esquálio'),
('Rio da Floresta','6:00-19:00','Verão','Sol/Chuva','Dourado'),
('Oceano','6:00-11:00/18:00-2:00','Outono/Inverno','Sol/Chuva','Albacora'),
('Rio da Cidade/Rio da Floresta','9:00-2:00','Primavera/Verão/Outono','Chuva','Alocine'),
('Rio da Cidade/Rio da Floresta/Lago da Montanha','06:00-02:00','Inverno','Sol/Chuva','Ófis'),
('Oceano/Lago da Montanha','6:00-11:00/19:00-2:00','Primavera/Verão/Inverno','Sol/Chuva','Halibute'),
('Lago do Bosque Secreto','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Madeirão'),
('Pântano da Bruxa','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Salmão nulo'),
('Esgotos','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Salmão Mutante'),
('Oceano da Ilha Gengibre','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Peixe-leão'),
('Lago da Ilha Gengibre/Rio da Ilha Gengibre','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Acará-disco-azul'),
('Cachoeira da Floresta','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Gobi'),
('Oceano da Ilha Gengibre','6:00-20:00','Verão','Sol/Chuva','Arraia'),
('Oceano mercado noturno','22:00-2:00','Outono/Inverno','Sol/Chuva','Lula da meia-noite'),
('Oceano mercado noturno','12:00-16:00','Outono','Sol/Chuva','Peixe assustador'),
('Oceano mercado noturno','06:00-02:00','Verão','Sol/Chuva','Peixe-bolha'),
('Oceano','06:00-02:00','Verão','Sol/Chuva','Peixe-carmim'),
('Rio da Cidade','06:00-02:00','Outono','Sol/Chuva','Tamboril'),
('Lago da Montanha','06:00-02:00','Primavera','Chuva','Lenda'),
('Rio da Floresta','06:00-02:00','Inverno','Sol/Chuva','Peixe-gelo'),
('Esgotos','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Carpa mutante'),
('Oceano','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Filho do peixe-carmim'),
('Rio da Cidade','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Senhorita tamboril'),
('Lago da Montanha','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Lenda 2'),
('Rio da Floresta','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Peixe-gelo júnior'),
('Esgotos','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Carpa radioativa'),
('Covo',NULL,'Primavera/Verão/Outono/Inverno','Sol/Chuva','Lagosta'),
('Covo',NULL,'Primavera/Verão/Outono/Inverno','Sol/Chuva','Concha'),
('Covo',NULL,'Primavera/Verão/Outono/Inverno','Sol/Chuva','Caranguejo'),
('Covo',NULL,'Primavera/Verão/Outono/Inverno','Sol/Chuva','Berbigão'),
('Covo',NULL,'Primavera/Verão/Outono/Inverno','Sol/Chuva','Mexilhão'),
('Covo',NULL,'Primavera/Verão/Outono/Inverno','Sol/Chuva','Camarão'),
('Covo',NULL,'Primavera/Verão/Outono/Inverno','Sol/Chuva','Ostra'),
('Covo',NULL,'Primavera/Verão/Outono/Inverno','Sol/Chuva','Lagostim'),
('Covo',NULL,'Primavera/Verão/Outono/Inverno','Sol/Chuva','Lesma'),
('Covo',NULL,'Primavera/Verão/Outono/Inverno','Sol/Chuva','Caramujo'),
('Oceano/Oceano da Ilha Gengibre','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Algas marinhas'),
('Rio da Cidade/Rio da Floresta/Deserto/Lago da Montanha/Lago do Bosque Secreto/Lago da Ilha Gengibre/Rio da Ilha Gengibre/Lago da Floresta','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Algas verdes'),
('Mina/Esgostos/Pântano da Bruxa','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Algas brancas'),
('Oceano','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Geléia do mar'),
('Rio da Cidade/Rio da Floresta/Deserto/Lago da Montanha/Lago do Bosque Secreto/Lago da Ilha Gengibre/Rio da Ilha Gengibre/Lago da Floresta','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Geléia do rio'),
('Mina','06:00-02:00','Primavera/Verão/Outono/Inverno','Sol/Chuva','Geléia da caverna');



